"""Initial migration

Revision ID: a660955623be
Revises: 
Create Date: 2026-04-22 18:01:08.711871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a660955623be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icao', sa.String(length=4), nullable=False),
    sa.Column('iata', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('runways', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airports_iata'), 'airports', ['iata'], unique=False)
    op.create_index(op.f('ix_airports_icao'), 'airports', ['icao'], unique=True)
    op.create_table('shared_aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('engine_type', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('max_range_nm', sa.Integer(), nullable=True),
    sa.Column('service_ceiling_ft', sa.Integer(), nullable=True),
    sa.Column('max_speed_kts', sa.Integer(), nullable=True),
    sa.Column('empty_weight_lb', sa.Integer(), nullable=True),
    sa.Column('max_takeoff_weight_lb', sa.Integer(), nullable=True),
    sa.Column('equip_codes', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_aircraft_registration'), 'shared_aircraft', ['registration'], unique=False)
    op.create_index(op.f('ix_shared_aircraft_type'), 'shared_aircraft', ['type'], unique=False)
    op.create_table('shared_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('calculations', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('runways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=5), nullable=True),
    sa.Column('surface', sa.String(length=50), nullable=True),
    sa.Column('length_m', sa.Integer(), nullable=True),
    sa.Column('width_m', sa.Integer(), nullable=True),
    sa.Column('lighting', sa.String(length=20), nullable=True),
    sa.Column('heading', sa.Integer(), nullable=True),
    sa.Column('pattern_altitude', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runways_airport_id', 'runways', ['airport_id'], unique=False)
    op.create_table('user_aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shared_aircraft_id', sa.Integer(), nullable=True),
    sa.Column('reg', sa.String(length=20), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('aircraft_type', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('total_time', sa.Float(), nullable=True),
    sa.Column('last_flown', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shared_aircraft_id'], ['shared_aircraft.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_aircraft_user_id', 'user_aircraft', ['user_id'], unique=False)
    op.create_index('ix_user_aircraft_user_reg', 'user_aircraft', ['user_id', 'reg'], unique=True)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('regulation', sa.String(length=10), nullable=True),
    sa.Column('home_airport', sa.String(length=4), nullable=True),
    sa.Column('currency_view', sa.String(length=10), nullable=True),
    sa.Column('time_format', sa.String(length=10), nullable=True),
    sa.Column('preferences', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('user_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shared_template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('calculations', sa.JSON(), nullable=True),
    sa.Column('is_modified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['shared_template_id'], ['shared_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_templates_user_id', 'user_templates', ['user_id'], unique=False)
    op.create_index('ix_user_templates_user_name', 'user_templates', ['user_id', 'name'], unique=False)
    op.drop_table('settings')
    op.drop_table('approaches')
    op.drop_table('flight_templates')
    op.drop_table('aircraft')
    op.add_column('currency_events', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('currency_events', sa.Column('flight_id', sa.Integer(), nullable=True))
    op.alter_column('currency_events', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('currency_events', 'date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('currency_events', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('currency_events', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('currency_events', 'instructor',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('currency_events', 'expiry',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_index(op.f('ix_currency_events_expiry'), 'currency_events', ['expiry'], unique=False)
    op.create_index('ix_currency_events_user_id', 'currency_events', ['user_id'], unique=False)
    op.create_foreign_key(None, 'currency_events', 'flights', ['flight_id'], ['id'])
    op.create_foreign_key(None, 'currency_events', 'users', ['user_id'], ['id'])
    op.add_column('flights', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('flights', sa.Column('aircraft_reg', sa.String(length=20), nullable=True))
    op.add_column('flights', sa.Column('departure_id', sa.Integer(), nullable=True))
    op.add_column('flights', sa.Column('arrival_id', sa.Integer(), nullable=True))
    op.add_column('flights', sa.Column('simulated_imc', sa.Float(), nullable=True))
    op.add_column('flights', sa.Column('approaches', sa.JSON(), nullable=True))
    op.add_column('flights', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('flights', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('flights', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('flights', 'date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('flights', 'start_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('flights', 'takeoff_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('flights', 'landing_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('flights', 'shutdown_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('flights', 'air_time',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('flights', 'pic',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('flights', 'sic',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'dual',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'night',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('flights', 'ifr',
               existing_type=sa.BOOLEAN(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'actual_imc',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('flights', 'xc',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'xc_over_50nm',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'right_seat',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'multi_pilot',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'pilot_flying',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'multi_engine',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'complex',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'high_performance',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'turbine',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'jet',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'route',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('flights', 'pic_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('flights', 'sic_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('flights', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_flights_date'), 'flights', ['date'], unique=False)
    op.create_index('ix_flights_user_aircraft', 'flights', ['user_id', 'aircraft_reg'], unique=False)
    op.create_index('ix_flights_user_date', 'flights', ['user_id', 'date'], unique=False)
    op.create_index('ix_flights_user_id', 'flights', ['user_id'], unique=False)
    op.create_foreign_key(None, 'flights', 'airports', ['departure_id'], ['id'])
    op.create_foreign_key(None, 'flights', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'flights', 'user_aircraft', ['aircraft_reg'], ['reg'])
    op.create_foreign_key(None, 'flights', 'airports', ['arrival_id'], ['id'])
    op.drop_column('flights', 'vfr')
    op.drop_column('flights', 'from_ap')
    op.drop_column('flights', 'night_operation')
    op.drop_column('flights', 'aircraft')
    op.drop_column('flights', 'to_ap')
    op.drop_column('flights', 'type')
    op.drop_column('flights', 'simulated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('simulated', sa.REAL(), nullable=True))
    op.add_column('flights', sa.Column('type', sa.TEXT(), nullable=True))
    op.add_column('flights', sa.Column('to_ap', sa.TEXT(), nullable=True))
    op.add_column('flights', sa.Column('aircraft', sa.TEXT(), nullable=True))
    op.add_column('flights', sa.Column('night_operation', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.add_column('flights', sa.Column('from_ap', sa.TEXT(), nullable=True))
    op.add_column('flights', sa.Column('vfr', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_index('ix_flights_user_id', table_name='flights')
    op.drop_index('ix_flights_user_date', table_name='flights')
    op.drop_index('ix_flights_user_aircraft', table_name='flights')
    op.drop_index(op.f('ix_flights_date'), table_name='flights')
    op.alter_column('flights', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('flights', 'sic_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('flights', 'pic_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('flights', 'route',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('flights', 'jet',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'turbine',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'high_performance',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'complex',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'multi_engine',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'pilot_flying',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'multi_pilot',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'right_seat',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'xc_over_50nm',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'xc',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'actual_imc',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('flights', 'ifr',
               existing_type=sa.Float(),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'night',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('flights', 'dual',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'sic',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('flights', 'pic',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('flights', 'air_time',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('flights', 'shutdown_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('flights', 'landing_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('flights', 'takeoff_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('flights', 'start_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('flights', 'date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('flights', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('flights', 'updated_at')
    op.drop_column('flights', 'created_at')
    op.drop_column('flights', 'approaches')
    op.drop_column('flights', 'simulated_imc')
    op.drop_column('flights', 'arrival_id')
    op.drop_column('flights', 'departure_id')
    op.drop_column('flights', 'aircraft_reg')
    op.drop_column('flights', 'user_id')
    op.drop_constraint(None, 'currency_events', type_='foreignkey')
    op.drop_constraint(None, 'currency_events', type_='foreignkey')
    op.drop_index('ix_currency_events_user_id', table_name='currency_events')
    op.drop_index(op.f('ix_currency_events_expiry'), table_name='currency_events')
    op.alter_column('currency_events', 'expiry',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('currency_events', 'instructor',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('currency_events', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('currency_events', 'type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('currency_events', 'date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('currency_events', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('currency_events', 'flight_id')
    op.drop_column('currency_events', 'user_id')
    op.create_table('aircraft',
    sa.Column('reg', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('class', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('hp', sa.INTEGER(), nullable=True),
    sa.Column('equip', sa.TEXT(), nullable=True),
    sa.Column('home', sa.TEXT(), nullable=True),
    sa.Column('total_time', sa.REAL(), nullable=True),
    sa.Column('last_flown', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('hidden', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('reg')
    )
    op.create_table('flight_templates',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('visible_fields', sa.TEXT(), nullable=False),
    sa.Column('calculations', sa.TEXT(), nullable=False),
    sa.Column('defaults', sa.TEXT(), nullable=False),
    sa.Column('icon', sa.TEXT(), nullable=True),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('approaches',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('flight_id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('airport', sa.TEXT(), nullable=True),
    sa.Column('runway', sa.TEXT(), nullable=True),
    sa.Column('actual', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_index('ix_user_templates_user_name', table_name='user_templates')
    op.drop_index('ix_user_templates_user_id', table_name='user_templates')
    op.drop_table('user_templates')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index('ix_user_aircraft_user_reg', table_name='user_aircraft')
    op.drop_index('ix_user_aircraft_user_id', table_name='user_aircraft')
    op.drop_table('user_aircraft')
    op.drop_index('ix_runways_airport_id', table_name='runways')
    op.drop_table('runways')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('shared_templates')
    op.drop_index(op.f('ix_shared_aircraft_type'), table_name='shared_aircraft')
    op.drop_index(op.f('ix_shared_aircraft_registration'), table_name='shared_aircraft')
    op.drop_table('shared_aircraft')
    op.drop_index(op.f('ix_airports_icao'), table_name='airports')
    op.drop_index(op.f('ix_airports_iata'), table_name='airports')
    op.drop_table('airports')
    # ### end Alembic commands ###
